// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHju4poeQn2EPTSmXnzfD5GX-mkQiPMxU',
    appId: '1:870656375325:web:88f7badf10b5a498a5a4f4',
    messagingSenderId: '870656375325',
    projectId: 'taskapp-2dd57',
    authDomain: 'taskapp-2dd57.firebaseapp.com',
    storageBucket: 'taskapp-2dd57.appspot.com',
    measurementId: 'G-876JSEFDFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_av-a867JlSh59y0Nd9wzMaCgRWrMbE',
    appId: '1:870656375325:android:7b82ed42071c9b55a5a4f4',
    messagingSenderId: '870656375325',
    projectId: 'taskapp-2dd57',
    storageBucket: 'taskapp-2dd57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRUJrxaZa8KYej29FKe9SY5Nzsj4oVZ6w',
    appId: '1:870656375325:ios:4c6588f1b535dddea5a4f4',
    messagingSenderId: '870656375325',
    projectId: 'taskapp-2dd57',
    storageBucket: 'taskapp-2dd57.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRUJrxaZa8KYej29FKe9SY5Nzsj4oVZ6w',
    appId: '1:870656375325:ios:44e19f24854ba66da5a4f4',
    messagingSenderId: '870656375325',
    projectId: 'taskapp-2dd57',
    storageBucket: 'taskapp-2dd57.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
